trigger:
- main   # or AutomationProject if that's your branch

pool:
  vmImage: 'windows-latest'

steps:
# Install .NET 8 SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Restore and build solution
- script: |
    dotnet restore
    dotnet build --configuration Release
  displayName: 'Restore & Build'

# Install Playwright browsers
- script: |
    dotnet tool install --global Microsoft.Playwright.CLI
    playwright install --with-deps
  displayName: 'Install Playwright Browsers'

# ✅ Run Playwright Tests (default BaseUrl from appsettings.json = Vercel)
- script: |
    dotnet test --configuration Release --logger "trx;LogFileName=test_results.trx"
  displayName: 'Run Playwright Tests'

# Publish test results to Azure DevOps Tests tab
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TestResults/*.trx'
    testRunTitle: 'Playwright Tests'
  condition: succeededOrFailed()
