trigger:
- main  # or AutomationProject if that's your working branch

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet restore
  displayName: 'Restore dependencies'

- script: dotnet build --configuration Release
  displayName: 'Build project'

# ✅ Correct way to install Playwright browsers
- script: dotnet tool install --global Microsoft.Playwright.CLI
  displayName: 'Install Playwright CLI'

- script: pwsh -c "playwright install --with-deps"
  displayName: 'Install Playwright browsers'

- script: dotnet test --configuration Release --logger "trx;LogFileName=test_results.trx"
  displayName: 'Run Playwright Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true
